### ISSUE TITLE
HTML markup is removed from category descriptions when Yoast SEO is used

### ISSUE THREAD

**Issue by mklasen** [inpsyde/MultilingualPress-Yoast-SEO-Sync#12]
**Steps to reproduce**
1. Install latest versions of MLP Yoast(2.1.2) and MLP (3.3.0)
2. Connect one site
3. Create a category and fill the description using the WYSIWYG editor (and add some markup)
4. Go to the linked category in the other language
5. Save the linked category in the other language
6. The HTML markup in the original language is removed

**What should happen**
The HTML markup should be kept.

**What happened instead**
The HTML markup is removed.

**Notes**
- The WYSIWYG editor is added to term descriptions by the Yoast plugin
- MLP loads meta boxes for all terms on every term page
- The save action used by MLP removes all html tags from the description

**Comment by Kdamen1** [comment]
I have the same issue!

**Comment by mklasen** [comment]
@Dinamiko Any chance you can get me an update / confirmation on this issue?

**Comment by Dinamiko** [comment]
Hi @mklasen sorry for the delay in the response, this issue comes from MultilingualPress 3, we already have fixed it there and it will be included in the next release (3.3.1). 

In the meantime, here is how to apply the fix: 
In src/multilingualpress/TranslationUi/Term/MetaboxFields.php line 89, change this:
`'sanitize_textarea_field'`
for this:
`'wp_kses_post'`
